### PR TITLE
Safely extract host from email address

### PR DESCRIPTION
**Pull request by nakutahyali**
I made changes for this issue.

### CODE REVIEW

**Comment by asiffermann** [comment]
Hi @anilkutahyali and thank you for taking the time to submit this pull request!

This is a much better way to extract the domain part of an email address, but the issue #103 will need additional work to be closed (and a little bit of design of how the options should be automatically validated at startup). It is still a good first step though!

However, your change will break this unit test as the exception thrown is no longer a `System.NotSupportedException` but a `System.FormatException`:

https://github.com/asiffermann/proffer/blob/b584d2382d2afa2a467bf7c5bd46389ebf08e571/tests/Proffer.Email.Tests/EmailSenderTests.cs#L309-L330

The following should work:
```c#
[Theory]
[Bug("https://github.com/asiffermann/proffer/issues/103")]
[InlineData("bademail.com")]
[InlineData("joe@jim@bademail.com")]
public async Task Should_Throw_With_BadEmail(string badEmail)
{
    string mockupEmail = "mockup@getproffer.net";

    var fixture = new EmailFixture(new()
    {
        { "Email:Mockup:Recipients:0", mockupEmail }
    });

    IEmailSender emailSender = fixture.Services.GetRequiredService<IEmailSender>();

    string subject = "Hello!";
    string message = "Message in plain text";
    var recipient = new EmailAddress(badEmail, "Recipient");

    await Assert.ThrowsAsync<FormatException>(() => emailSender.SendEmailAsync(subject, message, recipient));
}
```

Could you consider update your pull request with the fixed unit test (and maybe some more inline data with bad email inputs)?
You should be able to run all tests with trait 'Category=UnitTest' on your local machine without needing any secret key.

Thanks again for you interest in this project!

**Comment by nakutahyali** [comment]
@asiffermann Hello, I am sorry for the missing parts because this was my first contribution to the an opensource project. Thank for your feedbacks. I made the arrangements that you wanted.  Could you check again please?

By the way, you said "A little bit of design of how the options should be automatically validated at startup". I did not understand this part, what did you wanted from me exactly and what can i do about this?

**Comment by asiffermann** [comment]
Thank you, it looks all good to me!

I'm sorry if my comment wasn't clear enough. I just wanted to say that your pull request couldn't close the whole issue #103, which contains the additional following acceptance criteria:
- _All email addresses arguments (recipients of all kinds, sender, reply-to...) should be validated with Guards._
- _The options providing email addresses (default sender, mockup...) should be validated at startup (using [.NET Core options validation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#options-validation) )_

I didn't expect you to fix it or do anything more, but just wanted to explain why I will only reference this pull request in the issue rather than allowing it to close completely #103 😊

Thanks again!

**Comment by nakutahyali** [comment]
Thank you too for your patient and clear instructions that you gave me. Have a nice day :)

**Pull request merged**
